import { MarketItem, Skill, WantedItem } from '../types';

export const SAMPLE_MARKET_ITEMS: MarketItem[] = [
  {
    id: 'sample-m1',
    userId: 'demo-u1',
    condoCode: '1111',
    parentNickname: 'Sarah',
    roomNumber: 'A-12-03',
    parentAvatarIcon: '👩',
    title: 'Baby Float Ring (Good Condition)',
    genre: 'Baby & Kids',
    description: 'Used only once. Perfect for babies to enjoy the pool safely.',
    price: 150,
    type: 'SALE',
    status: 'AVAILABLE',
    requestStatus: 'NONE',
    paymentMethod: 'CASH',
    pickupLocation: 'Central Red Bench, G Floor Lobby',
    pickupDateTime: 'Weekend afternoons',
    condition: 'A',
    comments: [],
    images: ['https://images.unsplash.com/photo-1562185000-12e4f02e10d8?auto=format&fit=crop&q=80&w=400'],
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    likes: ['demo-u2']
  },
  {
    id: 'sample-m2',
    userId: 'demo-u2',
    condoCode: '1111',
    parentNickname: 'David',
    roomNumber: 'B-05-10',
    parentAvatarIcon: '👨',
    title: 'IKEA Coffee Table',
    genre: 'Furniture',
    description: 'Moving out sale. Minor scratches on the surface.',
    price: 30,
    type: 'SALE',
    status: 'RESERVED',
    requestStatus: 'NONE',
    paymentMethod: 'TNG',
    pickupLocation: 'Lobby 3A Lounge Entrance',
    pickupDateTime: 'Anytime after 7pm',
    condition: 'B',
    comments: [],
    images: ['https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&q=80&w=400'],
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    buyerId: 'demo-u1',
    buyerNickname: 'Sarah',
    buyerAvatarIcon: '👩'
  },
  {
    id: 'sample-m3',
    userId: 'demo-u3',
    condoCode: '1111',
    parentNickname: 'Linda',
    roomNumber: 'C-22-01',
    parentAvatarIcon: '👩🏻',
    title: 'Free House Plants',
    genre: 'Plants & Flowers',
    description: 'Giving away some succulents as I have too many now!',
    price: 0,
    type: 'FREE',
    status: 'SOLD',
    requestStatus: 'NONE',
    paymentMethod: 'FREE',
    pickupLocation: '5F Gym Entrance',
    pickupDateTime: 'Friday morning',
    condition: 'S',
    comments: [],
    images: ['https://images.unsplash.com/photo-1545241047-6083a3684587?auto=format&fit=crop&q=80&w=400'],
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    buyerId: 'demo-u2',
    buyerNickname: 'David',
    buyerAvatarIcon: '👨'
  },
  {
    id: 'sample-m4',
    userId: 'demo-u4',
    condoCode: '1111',
    parentNickname: 'Ken',
    roomNumber: 'A-08-05',
    parentAvatarIcon: '🧔',
    title: 'Electric Kettle (Almost New)',
    genre: 'Home Appliances',
    description: 'Used only a few times. Selling because I got a new one.',
    price: 45,
    type: 'SALE',
    status: 'AVAILABLE',
    requestStatus: 'NONE',
    paymentMethod: 'TNG',
    pickupLocation: 'Demo Tower A Lobby',
    pickupDateTime: 'Weekdays after 6pm',
    condition: 'S',
    comments: [],
    images: ['https://images.unsplash.com/photo-1594213114663-d94db9b17125?auto=format&fit=crop&q=80&w=400'],
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'sample-m5',
    userId: 'demo-u3',
    condoCode: '1111',
    parentNickname: 'Linda',
    roomNumber: 'C-22-01',
    parentAvatarIcon: '👩🏻',
    title: 'Kids Bicycle (16 inch)',
    genre: 'Sports',
    description: 'Outgrown by my son. Still works perfectly fine.',
    price: 80,
    type: 'SALE',
    status: 'RESERVED',
    requestStatus: 'NONE',
    paymentMethod: 'CASH',
    pickupLocation: 'Sky Garden Level 25',
    pickupDateTime: 'Saturday morning',
    condition: 'B',
    comments: [],
    images: ['https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=400'],
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    buyerId: 'demo-u4',
    buyerNickname: 'Ken',
    buyerAvatarIcon: '🧔'
  }
];

export const SAMPLE_SKILLS: Skill[] = [
  {
    id: 'sample-s1',
    userId: 'demo-u4',
    condoCode: '1111',
    parentNickname: 'Ken',
    parentAvatarIcon: '🧔',
    roomNumber: 'A-08-05',
    title: 'Math Tutoring for Primary Kids',
    category: 'Academic & Tutoring',
    description: 'I am a retired teacher. Happy to help kids with their math homework.',
    type: 'OFFER',
    status: 'AVAILABLE',
    requestStatus: 'NONE',
    price: 'RM 40/hr',
    comments: [],
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'sample-s2',
    userId: 'demo-u1',
    condoCode: '1111',
    parentNickname: 'Sarah',
    parentAvatarIcon: '👩',
    roomNumber: 'A-12-03',
    title: 'Baking Workshop (Cookies)',
    category: 'Cooking & Baking',
    description: 'Learn how to make chocolate chip cookies! Max 3 people.',
    type: 'OFFER',
    status: 'RESERVED',
    requestStatus: 'NONE',
    requesterId: 'demo-u3',
    requesterNickname: 'Linda',
    requesterAvatarIcon: '👩🏻',
    price: 'Exchange for coffee beans',
    comments: [],
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'sample-s3',
    userId: 'demo-u2',
    condoCode: '1111',
    parentNickname: 'David',
    parentAvatarIcon: '👨',
    roomNumber: 'B-05-10',
    title: 'Need help with PC Setup',
    category: 'Tech & Digital',
    description: 'Just bought a new gaming PC and need help with cable management and setup.',
    type: 'REQUEST',
    status: 'AVAILABLE',
    requestStatus: 'NONE',
    price: 'RM 50',
    comments: [],
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString()
  }
];

export const SAMPLE_WANTED_ITEMS: WantedItem[] = [
  {
    id: 'sample-w1',
    userId: 'demo-u2',
    condoCode: '1111',
    parentNickname: 'David',
    roomNumber: 'B-05-10',
    parentAvatarIcon: '👨',
    title: 'Looking for a Tennis Racket',
    genre: 'Sports',
    description: 'Need a spare racket for a friend visiting next week.',
    hopePrice: 50,
    pickupLocation: 'Anywhere in the condo',
    preferredTiming: 'Before next Wednesday',
    images: ['https://images.unsplash.com/photo-1617083281297-af330b568711?auto=format&fit=crop&q=80&w=400'],
    comments: [],
    status: 'OPEN',
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'sample-w2',
    userId: 'demo-u3',
    condoCode: '1111',
    parentNickname: 'Linda',
    roomNumber: 'C-22-01',
    parentAvatarIcon: '👩🏻',
    title: 'Wanted: Empty Cardboard Boxes',
    genre: 'Others',
    description: 'Need about 10 large boxes for moving next month.',
    hopePrice: 0,
    pickupLocation: 'Will pick up from your unit',
    preferredTiming: 'Anytime this week',
    images: ['https://images.unsplash.com/photo-1524514587686-8260194efb4c?auto=format&fit=crop&q=80&w=400'],
    comments: [],
    status: 'OPEN',
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString()
  }
];
